# Generated by Django 3.2 on 2022-12-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер блока')),
                ('price', models.IntegerField(verbose_name='Стоимость за квадратный метр квартиры')),
                ('porch', models.IntegerField(verbose_name='Количество подъездов')),
                ('floors', models.IntegerField(verbose_name='Количество этажей')),
                ('apartments_on_floor', models.IntegerField(verbose_name='Количество квартир на этаж')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО владельца')),
                ('date_of_sale', models.DateField(blank=True, null=True, verbose_name='Дата продажи')),
                ('status', models.CharField(choices=[('Выкуп', 'выкупили'), ('Выкуп не до конца', 'не до конца'), ('Расторгнуто', 'расторг'), ('Не продано', 'не прод')], max_length=20, verbose_name='Статус')),
                ('total_area', models.IntegerField(verbose_name='общая площадь (кв.м)')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
            ],
        ),
    ]
