# Generated by Django 3.2 on 2022-12-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='block',
            new_name='bloc',
        ),
    ]
